version: '2'
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
        typescript:
          mass_threshold: 100
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
  - node_modules/
  - '**/__tests__/'
  - 'config/'
  - 'db/'
  - 'dist/'
  - 'features/'
  - '**/node_modules/'
  - 'script/'
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - 'Tests/'
  - '**/vendor/'
  - '**/*_test.go'
  - '**/*.d.ts'
  - '**/*.d.ts'
  - '**/*.eslintrc.json'
