version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@3
jobs:
  build:
    docker:
      - image: node:16.13.2

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      # - run:
      #     name: Setup Code Climate test-reporter
      #     command: |
      #       curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #       chmod +x ./cc-test-reporter

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test
      - run: npm run build

      - run: npm run test:coverage

      # Run coverage report for Code Climate
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
          when: always
      - run:
          name: Send coverage report to Code Climate
          command:
            # nyc report requires that nyc has already been run,
            # which creates the .nyc_output folder containing necessary data
            ./cc-test-reporter after-build -t lcov
          when: always

      # - run: # run tests
      #     name: Run Test and Coverage
      #     command: |
      #       ./cc-test-reporter before-build
      #       npm run test:coverage
      #       ./cc-test-reporter after-build --exit-code $?

      - codecov/upload:
          file: './coverage/clover.xml'

  # upload_coverage:
  #   docker:
  #     - image: node:16.13.2

  #   working_directory: ~/repo
  #   steps:
  #     - checkout

  #     - run: npm run test:coverage

  # - run: # run tests
  #     name: Run Test and Coverage
  #     command: |
  #       ./cc-test-reporter before-build
  #       npm run test:coverage
  #       ./cc-test-reporter after-build --exit-code $?

  # - codecov/upload:
  #     file: './coverage/clover.xml'

  # - run:
  #     name: Setup Code Climate test-reporter
  #     command: |
  #       curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  #       chmod +x ./cc-test-reporter

  # - run:
  #     name: Run Test and Coverage
  #     command: |
  #       ./cc-test-reporter before-build
  #       npm run test:coverage
  #       ./cc-test-reporter after-build --exit-code $?

  # - codecov/upload:
  #     file: './coverage/clover.xml'
  # - codecov/upload:
  #     file: './coverage/clover.xml'
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - upload_coverage:
#           # type: approval
#           requires:
#             - build
